project_id = "qmsidlazqaqwcptpsjqh"

[functions.admin-control-log]
verify_jwt = false

[functions.bgpview-enrich]
verify_jwt = false

[functions.cloudflare-radar-enrich]
verify_jwt = false

[functions.abuse-ch-validator]
verify_jwt = false

[functions.source-health-check]
verify_jwt = false

[functions.abuseipdb-validator]
verify_jwt = false

[functions.abuseipdb-enrich]
verify_jwt = false

[functions.feed]
verify_jwt = false

[functions.feed-get]
verify_jwt = false

[functions.ingest]
verify_jwt = false

[functions.schedule-validations]
verify_jwt = false

[functions.run-validations]
verify_jwt = false

[functions.daily-delta]
verify_jwt = false

[functions.email-dispatch]
verify_jwt = false

[functions.manual-ingest]
verify_jwt = false

[functions.urlscan-validator]
verify_jwt = false

[functions.honeydb-validator]
verify_jwt = false

[functions.neutrinoapi-validator]
verify_jwt = false

[functions.virustotal-validator]
verify_jwt = false

[functions.censys-validator]
verify_jwt = false

[functions.ripestat-enrich]
verify_jwt = false
