project_id = "qmsidlazqaqwcptpsjqh"

[functions.abuse-ch-validator]
verify_jwt = false

[functions.abuseipdb-validator]
verify_jwt = false

[functions.abuseipdb-enrich]
verify_jwt = false

[functions.feed]
verify_jwt = false

[functions.feed-get]
verify_jwt = false

[functions.ingest]
verify_jwt = false

[functions.schedule-validations]
verify_jwt = false

[functions.run-validations]
verify_jwt = false

[functions.daily-delta]
verify_jwt = false

[functions.email-dispatch]
verify_jwt = false

[functions.manual-ingest]
verify_jwt = false
