-- Add 84 Monty Security C2-Tracker sources (C2, Stealer, RAT, Loader, Botnet, Tools)
-- Updated weekly (Monday 02:00 UTC) via Shodan/Censys research

-- Insert all 84 sources
INSERT INTO ingest_sources (name, url, kind, enabled, priority, description) VALUES
-- C2 Frameworks (priority 90)
('Monty Security - C2 Framework - Cobalt Strike', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/cobalt_strike.txt', 'ipv4', true, 90, 'Cobalt Strike C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Metasploit Framework', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/metasploit_framework.txt', 'ipv4', true, 90, 'Metasploit Framework C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Covenant', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/covenant.txt', 'ipv4', true, 90, 'Covenant C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Mythic', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/mythic.txt', 'ipv4', true, 90, 'Mythic C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Brute Ratel C4', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/brute_ratel_c4.txt', 'ipv4', true, 90, 'Brute Ratel C4 C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - PoshC2', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/posh.txt', 'ipv4', true, 90, 'PoshC2 C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Sliver', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/sliver.txt', 'ipv4', true, 90, 'Sliver C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Deimos', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/deimos.txt', 'ipv4', true, 90, 'Deimos C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Panda', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/panda.txt', 'ipv4', true, 90, 'Panda C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Nimplant C2', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/nimplant_c2.txt', 'ipv4', true, 90, 'Nimplant C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Havoc C2', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/havoc_c2.txt', 'ipv4', true, 90, 'Havoc C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Caldera', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/caldera.txt', 'ipv4', true, 90, 'Caldera C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Empire', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/empire.txt', 'ipv4', true, 90, 'Empire C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Ares', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/ares.txt', 'ipv4', true, 90, 'Ares C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Hak5 Cloud C2', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/hak5_cloud_c2.txt', 'ipv4', true, 90, 'Hak5 Cloud C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Pantegana', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/pantegana.txt', 'ipv4', true, 90, 'Pantegana C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - SuperShell', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/supershell.txt', 'ipv4', true, 90, 'SuperShell C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - VShell', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/vshell.txt', 'ipv4', true, 90, 'VShell C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Villain', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/villain.txt', 'ipv4', true, 90, 'Villain C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - RedGuard C2', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/redguard_c2.txt', 'ipv4', true, 90, 'RedGuard C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - Oyster C2', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/oyster_c2.txt', 'ipv4', true, 90, 'Oyster C2 servers - Updated weekly via Shodan/Censys'),
('Monty Security - C2 Framework - BYOB C2', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/byob_c2.txt', 'ipv4', true, 90, 'BYOB C2 servers - Updated weekly via Shodan/Censys'),
-- Stealer (priority 85)
('Monty Security - Stealer - AcidRain Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/acidrain_stealer.txt', 'ipv4', true, 85, 'AcidRain Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Misha Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/misha_stealer.txt', 'ipv4', true, 85, 'Misha Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Patriot Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/patriot_stealer.txt', 'ipv4', true, 85, 'Patriot Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Raxnet Bitcoin Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/raxnet_bitcoin_stealer.txt', 'ipv4', true, 85, 'Raxnet Bitcoin Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Titan Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/titan_stealer.txt', 'ipv4', true, 85, 'Titan Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Collector Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/collector_stealer.txt', 'ipv4', true, 85, 'Collector Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Mystic Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/mystic_stealer.txt', 'ipv4', true, 85, 'Mystic Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Gotham Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/gotham_stealer.txt', 'ipv4', true, 85, 'Gotham Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Meduza Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/meduza_stealer.txt', 'ipv4', true, 85, 'Meduza Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - RisePro Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/risepro_stealer.txt', 'ipv4', true, 85, 'RisePro Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Bandit Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/bandit_stealer.txt', 'ipv4', true, 85, 'Bandit Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Mint Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/mint_stealer.txt', 'ipv4', true, 85, 'Mint Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Atlandida Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/atlandida_stealer.txt', 'ipv4', true, 85, 'Atlandida Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Atomic Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/atomic_stealer.txt', 'ipv4', true, 85, 'Atomic Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Lumma Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/lumma_stealer.txt', 'ipv4', true, 85, 'Lumma Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Serpent Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/serpent_stealer.txt', 'ipv4', true, 85, 'Serpent Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Axile Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/axile_stealer.txt', 'ipv4', true, 85, 'Axile Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Vector Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/vector_stealer.txt', 'ipv4', true, 85, 'Vector Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Z3us Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/z3us_stealer.txt', 'ipv4', true, 85, 'Z3us Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Rastro Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/rastro_stealer.txt', 'ipv4', true, 85, 'Rastro Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - DarkEye Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/darkeye_stealer.txt', 'ipv4', true, 85, 'DarkEye Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Agniane Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/agniane_stealer.txt', 'ipv4', true, 85, 'Agniane Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Epsilon Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/epsilon_stealer.txt', 'ipv4', true, 85, 'Epsilon Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Bahamut Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/bahamut_stealer.txt', 'ipv4', true, 85, 'Bahamut Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Vidar Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/vidar_stealer.txt', 'ipv4', true, 85, 'Vidar Stealer C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Stealer - Spectre Stealer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/spectre_stealer.txt', 'ipv4', true, 85, 'Spectre Stealer C2 - Updated weekly via Shodan/Censys'),
-- RAT/Trojan (priority 85)
('Monty Security - RAT/Trojan - Quasar RAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/quasar_rat.txt', 'ipv4', true, 85, 'Quasar RAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - ShadowPad', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/shadowpad.txt', 'ipv4', true, 85, 'ShadowPad C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - AsyncRAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/asyncrat.txt', 'ipv4', true, 85, 'AsyncRAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - DCRAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/dcrat.txt', 'ipv4', true, 85, 'DCRAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - BitRAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/bitrat.txt', 'ipv4', true, 85, 'BitRAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - DarkComet Trojan', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/darkcomet_trojan.txt', 'ipv4', true, 85, 'DarkComet Trojan C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - XtremeRAT Trojan', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/xtremerat_trojan.txt', 'ipv4', true, 85, 'XtremeRAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - NanoCore RAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/nanocore_rat_trojan.txt', 'ipv4', true, 85, 'NanoCore RAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - Gh0st RAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/gh0st_rat_trojan.txt', 'ipv4', true, 85, 'Gh0st RAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - DarkTrack RAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/darktrack_rat_trojan.txt', 'ipv4', true, 85, 'DarkTrack RAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - njRAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/njrat_trojan.txt', 'ipv4', true, 85, 'njRAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - Remcos Pro RAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/remcos_pro_rat_trojan.txt', 'ipv4', true, 85, 'Remcos Pro RAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - Poison Ivy', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/poison_ivy_trojan.txt', 'ipv4', true, 85, 'Poison Ivy C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - Orcus RAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/orcus_rat_trojan.txt', 'ipv4', true, 85, 'Orcus RAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - ZeroAccess Trojan', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/zeroaccess_trojan.txt', 'ipv4', true, 85, 'ZeroAccess Trojan C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - HookBot Trojan', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/hookbot_trojan.txt', 'ipv4', true, 85, 'HookBot Trojan C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - NetBus Trojan', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/netbus_trojan.txt', 'ipv4', true, 85, 'NetBus Trojan C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - Mekotio Trojan', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/mekotio_trojan.txt', 'ipv4', true, 85, 'Mekotio Trojan C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - Gozi Trojan', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/gozi_trojan.txt', 'ipv4', true, 85, 'Gozi Trojan C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - VenomRAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/venomrat.txt', 'ipv4', true, 85, 'VenomRAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - BlackDolphin', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/blackdolphin.txt', 'ipv4', true, 85, 'BlackDolphin C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - Artemis RAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/artemis_rat.txt', 'ipv4', true, 85, 'Artemis RAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - SpyAgent', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/spyagent.txt', 'ipv4', true, 85, 'SpyAgent C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - SpiceRAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/spicerat.txt', 'ipv4', true, 85, 'SpiceRAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - Dust RAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/dust_rat.txt', 'ipv4', true, 85, 'Dust RAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - Pupy RAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/pupy_rat.txt', 'ipv4', true, 85, 'Pupy RAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - Kraken RAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/kraken_rat.txt', 'ipv4', true, 85, 'Kraken RAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - Viper RAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/viper_rat.txt', 'ipv4', true, 85, 'Viper RAT C2 - Updated weekly via Shodan/Censys'),
('Monty Security - RAT/Trojan - SecTop RAT', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/sectop_rat.txt', 'ipv4', true, 85, 'SecTop RAT C2 - Updated weekly via Shodan/Censys'),
-- Loader (priority 80)
('Monty Security - Loader - Godzilla Loader', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/godzilla_loader.txt', 'ipv4', true, 80, 'Godzilla Loader C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Loader - Jinx Loader', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/jinx_loader.txt', 'ipv4', true, 80, 'Jinx Loader C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Loader - Netpune Loader', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/netpune_loader.txt', 'ipv4', true, 80, 'Netpune Loader C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Loader - Bumblebee Loader', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/bumblebee_loader.txt', 'ipv4', true, 80, 'Bumblebee Loader C2 - Updated weekly via Shodan/Censys'),
-- Malware Altri (priority 75)
('Monty Security - Malware Other - UNAM Web Panel', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/unam_web_panel.txt', 'ipv4', true, 75, 'UNAM Web Panel - Updated weekly via Shodan/Censys'),
-- Tools (priority 70)
('Monty Security - Tool - XMRig Monero Cryptominer', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/xmrig_monero_cryptominer.txt', 'ipv4', true, 70, 'XMRig Monero Cryptominer - Updated weekly via Shodan/Censys'),
('Monty Security - Tool - GoPhish', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/gophish.txt', 'ipv4', true, 70, 'GoPhish servers - Updated weekly via Shodan/Censys'),
('Monty Security - Tool - Browser Exploitation Framework', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/browser_exploitation_framework.txt', 'ipv4', true, 70, 'Browser Exploitation Framework - Updated weekly via Shodan/Censys'),
('Monty Security - Tool - BurpSuite', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/burpsuite.txt', 'ipv4', true, 70, 'BurpSuite servers - Updated weekly via Shodan/Censys'),
('Monty Security - Tool - Hashcat', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/hashcat.txt', 'ipv4', true, 70, 'Hashcat servers - Updated weekly via Shodan/Censys'),
('Monty Security - Tool - MobSF', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/mobsf.txt', 'ipv4', true, 70, 'MobSF servers - Updated weekly via Shodan/Censys'),
('Monty Security - Tool - EvilGoPhish', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/evilgophish.txt', 'ipv4', true, 70, 'EvilGoPhish servers - Updated weekly via Shodan/Censys'),
('Monty Security - Tool - Evilginx', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/evilginx.txt', 'ipv4', true, 70, 'Evilginx servers - Updated weekly via Shodan/Censys'),
-- Botnets (priority 90)
('Monty Security - Botnet - 7777 Botnet', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/7777.txt', 'ipv4', true, 90, '7777 Botnet C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Botnet - BlackNet Botnet', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/blacknet.txt', 'ipv4', true, 90, 'BlackNet Botnet C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Botnet - Doxerina Botnet', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/doxerina.txt', 'ipv4', true, 90, 'Doxerina Botnet C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Botnet - Scarab Botnet', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/scarab.txt', 'ipv4', true, 90, 'Scarab Botnet C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Botnet - 63256 Botnet', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/63256.txt', 'ipv4', true, 90, '63256 Botnet C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Botnet - Kaiji Botnet', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/kaiji.txt', 'ipv4', true, 90, 'Kaiji Botnet C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Botnet - Moobot Botnet', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/moobot.txt', 'ipv4', true, 90, 'Moobot Botnet C2 - Updated weekly via Shodan/Censys'),
('Monty Security - Botnet - Mozi Botnet', 'https://raw.githubusercontent.com/montysecurity/C2-Tracker/main/data/mozi.txt', 'ipv4', true, 90, 'Mozi Botnet C2 - Updated weekly via Shodan/Censys')
ON CONFLICT (name) DO UPDATE SET enabled = EXCLUDED.enabled, priority = EXCLUDED.priority, description = EXCLUDED.description, updated_at = now();

-- Schedule weekly sync (Monday 02:00 UTC)
SELECT cron.schedule('montysecurity-c2-tracker-weekly-sync', '0 2 * * 1', 'SELECT _call_edge(''montysecurity-c2-tracker-sync'')');

-- Trigger immediate first ingest
SELECT net.http_post(url := 'https://qmsidlazqaqwcptpsjqh.functions.supabase.co/montysecurity-c2-tracker-sync', headers := jsonb_build_object('Content-Type', 'application/json', 'Authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtc2lkbGF6cWFxd2NwdHBzanFoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTMwMzE1NywiZXhwIjoyMDc0ODc5MTU3fQ.WKzTXRt8vhOlpCqLfM_bOKIQ1vJZKaKdECVSqW-8T3Y', 'x-cron-secret', 'INTELGUARD_Cr0N2025@2025'), body := jsonb_build_object('timestamp', now(), 'triggered_by', 'initial_setup'));